# -*- coding: utf-8 -*-
"""counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AIES6muq9O8wECR9qnLmqiSp02OgTvWf
"""

grade=input()